---
title           : "Hugo | Starterkit Boilerplate"
baseURL         : "https://ukaric.github.io/Hugo-Build/"
languageCode    : "en-us"
metaDataFormat  : "yaml"
paginate        : 0
buildDrafts     : false
buildFuture     : true
disable404      : true
enableRobotsTXT : true
watch           : true

archetypedir  : "src/archetypes"
contentdir    : "src/content"
dataDir       : "src/data"
layoutdir     : "src/layouts"
publishdir    : "build/production"
staticdir     : "src/static"
themesdir     : "src/themes"
...
